version: '3.8'

services:
  app:
    build: .
    # image: docker.pkg.github.com/click-flow/docker-images/lambda-hydrator:v1-alpine
    image: ghcr.io/click-flow/docker-images/lambda-hydrator:v1-alpine
