version: '3'

services:
  terraform-0.13:
    build:
      args:
        TERRAFORM_VERSION: 0.13.3
      context: .
    image: docker.pkg.github.com/click-flow/docker-images/terraform:v0.13.3-alpine
  terraform-0.14:
    build:
      args:
        TERRAFORM_VERSION: 0.14.0-alpha20200910
      context: .
    image: docker.pkg.github.com/click-flow/docker-images/terraform:v0.14.0-alpine

